/**
 * exportProject.ts — Export utilities for AI Cine Director projects
 * Supports: JSON dump, Shot Bible (markdown text), CSV scene list
 */
import { StoryboardProject } from '../types';

// ─── JSON Export ─────────────────────────────────────────────────────────────

export function exportProjectJson(project: StoryboardProject): void {
  const json = JSON.stringify(project, null, 2);
  downloadText(json, `${slugify(project.project_title || 'project')}.json`, 'application/json');
}

// ─── Shot Bible (Markdown) ────────────────────────────────────────────────────

export function exportShotBible(project: StoryboardProject): void {
  const lines: string[] = [];

  lines.push(`# 🎬 SHOT BIBLE — ${project.project_title || 'Untitled Project'}`);
  lines.push(`*Generated by AI Cine Director*`);
  lines.push('');

  if (project.logline) {
    lines.push(`## Logline`);
    lines.push(`> ${project.logline}`);
    lines.push('');
  }

  if (project.world_setting) {
    lines.push(`## World Setting`);
    lines.push(project.world_setting);
    lines.push('');
  }

  if (project.character_anchor || (project.story_entities && project.story_entities.length > 0)) {
    lines.push(`## Character Bible`);
    if (project.story_entities && project.story_entities.length > 0) {
      for (const entity of project.story_entities) {
        lines.push(`### ${entity.name} (${entity.type})`);
        if (entity.description) lines.push(entity.description);
        lines.push('');
      }
    } else if (project.character_anchor) {
      lines.push(project.character_anchor);
      lines.push('');
    }
  }

  if (project.director_controls) {
    const dc = project.director_controls;
    lines.push(`## Director Controls`);
    const dcEntries: [string, unknown][] = Object.entries(dc)
      .filter(([, v]) => v !== undefined && v !== null && v !== '' && v !== 0);
    for (const [k, v] of dcEntries) {
      if (typeof v === 'object') {
        lines.push(`- **${camelToTitle(k)}**: ${JSON.stringify(v)}`);
      } else {
        lines.push(`- **${camelToTitle(k)}**: ${v}`);
      }
    }
    lines.push('');
  }

  lines.push(`## Scenes & Shots`);
  lines.push('');

  for (const scene of (project.scenes || [])) {
    lines.push(`---`);
    lines.push(`### Scene ${scene.scene_number}${scene.scene_title ? ` — ${scene.scene_title}` : ''}`);
    lines.push('');

    if (scene.visual_description) {
      lines.push(`**Visual:** ${scene.visual_description}`);
    }
    if (scene.audio_description) {
      lines.push(`**Audio:** ${scene.audio_description}`);
    }
    if (scene.dramatic_function) {
      lines.push(`**Dramatic Function:** ${scene.dramatic_function}`);
    }
    if (scene.tension_level !== undefined) {
      lines.push(`**Tension Level:** ${'█'.repeat(Math.round(scene.tension_level / 10 * 10))} ${scene.tension_level}/10`);
    }
    if (scene.shot_type) {
      lines.push(`**Camera:** ${scene.shot_type}`);
    }
    if (scene.image_url) {
      lines.push(`**Frame:** ${scene.image_url}`);
    }
    if (scene.video_url) {
      lines.push(`**Video:** ${scene.video_url}`);
    }
    if (scene.image_prompt) {
      lines.push('');
      lines.push(`> *Image Prompt:* ${scene.image_prompt}`);
    }

    // Shots (stored on the scene as shots array from the pipeline)
    const shots: any[] = (scene as any).shots || [];
    if (shots.length > 0) {
      lines.push('');
      lines.push(`#### Shot List`);
      for (const shot of shots) {
        lines.push(`- **Shot ${shot.shot_number}** [${shot.camera_angle}/${shot.camera_movement}] — ${shot.action} *(${shot.duration_sec}s)*`);
      }
    }
    lines.push('');
  }

  downloadText(lines.join('\n'), `${slugify(project.project_title || 'shot-bible')}_shot-bible.md`, 'text/markdown');
}

// ─── CSV Scene List ───────────────────────────────────────────────────────────

export function exportScenesCsv(project: StoryboardProject): void {
  const headers = [
    'scene_number', 'scene_title', 'dramatic_function', 'tension_level',
    'shot_type', 'visual_description', 'audio_description',
    'image_url', 'video_url'
  ];

  const rows = (project.scenes || []).map(scene => [
    scene.scene_number,
    (scene as any).scene_title || '',
    (scene as any).dramatic_function || '',
    (scene as any).tension_level ?? '',
    scene.shot_type || '',
    escapeCsv(scene.visual_description || ''),
    escapeCsv(scene.audio_description || ''),
    scene.image_url || '',
    scene.video_url || '',
  ]);

  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  downloadText(csv, `${slugify(project.project_title || 'scenes')}_scenes.csv`, 'text/csv');
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function downloadText(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function slugify(str: string): string {
  return str.toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fff]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'project';
}

function escapeCsv(str: string): string {
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function camelToTitle(str: string): string {
  return str.replace(/([A-Z])/g, ' $1')
    .replace(/^./, s => s.toUpperCase())
    .trim();
}
