#!/bin/bash

# ============================================
# AI Cine Director - Test Commands Quick Reference
# ============================================

echo "🎬 AI Cine Director - Testing Commands"
echo "=========================================="
echo ""
echo "📋 PREREQUISITE:"
echo "   Make sure backend is running:"
echo "   npm run server"
echo ""
echo "=========================================="
echo ""
echo "1️⃣  API Integration Tests (Recommended to run first)"
echo "   Command: npm run test:api"
echo "   Tests:"
echo "     • Missing Character Anchor Auto-Correction"
echo "     • Insufficient Credits Guard"
echo "     • Character Consistency Keywords Enforcement"
echo "     • Image Prompt Consistency"
echo ""
echo "2️⃣  API Tests with Watch Mode (Re-run on changes)"
echo "   Command: npm run test:api:watch"
echo ""
echo "3️⃣  Full Stress Test Suite (For production validation)"
echo "   Command: npm run stress-test"
echo "   Tests:"
echo "     • Single Credit Deduction"
echo "     • Concurrent Deductions (Race Condition Prevention)"
echo "     • Character Anchor Consistency Enforcement"
echo "     • Reserve → Finalize → Refund Flow"
echo "     • Insufficient Credits Guard"
echo "     • Negative Credit Prevention"
echo "     • Concurrent Storyboard Generation"
echo "     • Auth Token Validation"
echo "     • Video Motion Prompt Consistency"
echo "     • Error Recovery & Refund"
echo ""
echo "4️⃣  Stress Tests with Watch Mode"
echo "   Command: npm run stress-test:watch"
echo ""
echo "=========================================="
echo ""
echo "🚀 Quick Start (All in one):"
echo ""
echo "   # Terminal 1: Start backend"
echo "   npm run server"
echo ""
echo "   # Terminal 2: Run API tests"
echo "   npm run test:api"
echo ""
echo "   # Terminal 3 (Optional): Run full stress test"
echo "   npm run stress-test"
echo ""
echo "=========================================="
echo ""
echo "✅ Recommended Test Flow:"
echo ""
echo "   1. npm run test:api          (15-30 seconds)"
echo "   2. npm run stress-test       (2-5 minutes)"
echo "   3. Manual frontend testing   (5-10 minutes)"
echo ""
echo "=========================================="
echo ""
